# CREATING ARRAYS

In [16]:
import numpy as np
a1=np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])
ab=np.array([["a"],["b"],["c"],["d"],["e"],["f"]])
a2=np.zeros(10)
a3=np.ones(10)
a4=np.random.random(10)
a5=np.random.randn(10)
a6=np.linspace(0,10,100)
a7=np.arange(0,10,0.02)

In [17]:
ab

array([['a'],
       ['b'],
       ['c'],
       ['d'],
       ['e'],
       ['f']], dtype='<U1')

In [6]:
a1

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [14]:
a1*11,a1*12,a1*13,a1*14

(array([[ 11],
        [ 22],
        [ 33],
        [ 44],
        [ 55],
        [ 66],
        [ 77],
        [ 88],
        [ 99],
        [110]]),
 array([[ 12],
        [ 24],
        [ 36],
        [ 48],
        [ 60],
        [ 72],
        [ 84],
        [ 96],
        [108],
        [120]]),
 array([[ 13],
        [ 26],
        [ 39],
        [ 52],
        [ 65],
        [ 78],
        [ 91],
        [104],
        [117],
        [130]]),
 array([[ 14],
        [ 28],
        [ 42],
        [ 56],
        [ 70],
        [ 84],
        [ 98],
        [112],
        [126],
        [140]]))

In [8]:
a6

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [11]:
a1

array([[2, 3, 4, 5],
       [2, 3, 4, 5],
       [4, 5, 6, 7]])

In [12]:
a2

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
a3

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
a4

array([0.11734584, 0.95572576, 0.19268591, 0.4641149 , 0.28690682,
       0.14043325, 0.08447501, 0.85265888, 0.68969072, 0.66243472])

In [15]:
a5

array([ 0.25895846,  1.51323449,  1.78349989, -1.63889465,  0.38451386,
       -1.28057355,  0.79400927,  0.114954  ,  0.4872199 ,  1.14518479])

In [16]:
a7

array([0.  , 0.02, 0.04, 0.06, 0.08, 0.1 , 0.12, 0.14, 0.16, 0.18, 0.2 ,
       0.22, 0.24, 0.26, 0.28, 0.3 , 0.32, 0.34, 0.36, 0.38, 0.4 , 0.42,
       0.44, 0.46, 0.48, 0.5 , 0.52, 0.54, 0.56, 0.58, 0.6 , 0.62, 0.64,
       0.66, 0.68, 0.7 , 0.72, 0.74, 0.76, 0.78, 0.8 , 0.82, 0.84, 0.86,
       0.88, 0.9 , 0.92, 0.94, 0.96, 0.98, 1.  , 1.02, 1.04, 1.06, 1.08,
       1.1 , 1.12, 1.14, 1.16, 1.18, 1.2 , 1.22, 1.24, 1.26, 1.28, 1.3 ,
       1.32, 1.34, 1.36, 1.38, 1.4 , 1.42, 1.44, 1.46, 1.48, 1.5 , 1.52,
       1.54, 1.56, 1.58, 1.6 , 1.62, 1.64, 1.66, 1.68, 1.7 , 1.72, 1.74,
       1.76, 1.78, 1.8 , 1.82, 1.84, 1.86, 1.88, 1.9 , 1.92, 1.94, 1.96,
       1.98, 2.  , 2.02, 2.04, 2.06, 2.08, 2.1 , 2.12, 2.14, 2.16, 2.18,
       2.2 , 2.22, 2.24, 2.26, 2.28, 2.3 , 2.32, 2.34, 2.36, 2.38, 2.4 ,
       2.42, 2.44, 2.46, 2.48, 2.5 , 2.52, 2.54, 2.56, 2.58, 2.6 , 2.62,
       2.64, 2.66, 2.68, 2.7 , 2.72, 2.74, 2.76, 2.78, 2.8 , 2.82, 2.84,
       2.86, 2.88, 2.9 , 2.92, 2.94, 2.96, 2.98, 3.

In [17]:
2*a1

array([[ 4,  6,  8, 10],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14]])

In [18]:
a1[a1>4]

array([5, 5, 5, 6, 7])

In [20]:
1/a1+a1+2

array([[4.5       , 5.33333333, 6.25      , 7.2       ],
       [4.5       , 5.33333333, 6.25      , 7.2       ],
       [6.25      , 7.2       , 8.16666667, 9.14285714]])

In [21]:
x=np.linspace(0,1,100)

In [22]:
x

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [23]:
import matplotlib
from matplotlib import pyplot as plt

In [24]:
plt.plot(x,x**2)

In [25]:
plt.hist(a4)


(array([3., 1., 1., 0., 1., 0., 2., 0., 1., 1.]),
 array([0.08447501, 0.17160008, 0.25872516, 0.34585023, 0.43297531,
        0.52010038, 0.60722546, 0.69435054, 0.78147561, 0.86860069,
        0.95572576]),
 <BarContainer object of 10 artists>)